### PR TITLE
Mgii system

### PR DESCRIPTION
**Pull request by profxj**
Adds a MgII child to IGMSystem.

Updates the script too and removes
NHI as required.

Updates doc

### CODE REVIEW

**Comment by marijana777** [comment]
Travis CI build is failing for Mgii system branch and for Master branch.

**Comment by marijana777** [comment]
Travis CI build tests are failing for Mgii system branch and for Master branch.

**Comment by profxj** [comment]
Now passing tests on my machine.  @marijana777 , you can ignore Travis
for now.

**Comment by marijana777** [comment]
Ok. Ignoring Travis (It looks like failing again)

**Pull request merged**
