### PR TITLE
Hot fix for the LLS script

### PR DESCRIPTION
**Pull request by profxj**
should work

### CODE REVIEW

**Comment by jsribaud** [comment]
This seemed to break and prevent me from even launching the gui. See below for error.



multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/jsribaud/python/pyigm/pyigm/fN/tau_eff.py", line 261, in map_lymanew
    wrest=dict_inp['wrest'])#EW_spline=dict_inp['EW_spline'],
  File "/Users/jsribaud/python/pyigm/pyigm/fN/tau_eff.py", line 211, in lyman_ew
    zeval = ((Lambda / line) - 1).value
  File "/anaconda/lib/python3.6/site-packages/astropy/units/quantity.py", line 620, in __array_ufunc__
    converters, unit = converters_and_unit(function, method, *inputs)
  File "/anaconda/lib/python3.6/site-packages/astropy/units/quantity_helper.py", line 567, in converters_and_unit
    .format(function.__name__))
astropy.units.core.UnitsError: Can only apply 'subtract' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda/bin/pyigm_fitlls", line 11, in <module>
    load_entry_point('pyigm', 'console_scripts', 'pyigm_fitlls')()
  File "/Users/jsribaud/python/pyigm/pyigm/scripts/pyigm_fitlls.py", line 100, in main
    lls_fit_file=pargs.lls_fit_file)
  File "/Users/jsribaud/python/pyigm/pyigm/guis/fitlls.py", line 192, in __init__
    igm=(self.conti_dict['igm']=='True'))
  File "/Users/jsribaud/python/pyigm/pyigm/continuum/quasar.py", line 91, in get_telfer_spec
    ateff = pool.map(pyift.map_lymanew, adict)
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
astropy.units.core.UnitsError: Can only apply 'subtract' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)

**Comment by profxj** [comment]
crap..

Will see if I can get back to this today (heavily
distracted by other matters)

**Comment by jsribaud** [comment]
I take it back, the previous error was due to being on the wrong branch. Switched over the lls_script branch, still crashing with 'C' and 'A' keystrokes.

**Comment by jsribaud** [comment]
And oddly enough, if '#' is used first to set continuum level, 'C' simply resets the continuum level with no crash. Haven't figured out any instance where 'A' works and sets an LLS.

**Comment by profxj** [comment]
@astronomeara -- How is it working for you?
I forget if we were even supposed to use 'A'  ;)

**Comment by astronomeara** [comment]
Haven’t yet had a chance, will do in a bit

**Comment by astronomeara** [comment]
Can confirm that it now launches correctly, but cannot set a unit continuum without a crash.

**Comment by marijana777** [comment]
if useful, issues/199 might be relevant. I also wrote how it is working for me..

**Comment by profxj** [comment]
Several updates made.  I think things are now working.

@astronomeara can you try again?

**Comment by astronomeara** [comment]
No dice.  Pulled from lls_script branch.

pyigm_fitlls J111610.69+411814.4_4545.0.fits 3.0

Then gui launches (yay!).  This time, un-normalized but w/ a pink continuum estimate. (yay?)

If I hit either 'C' or 'R' or 'D', gui crashes with following:
  File "/Users/jomeara/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 322, in keyPressEvent
    FigureCanvasBase.key_press_event(self, key, guiEvent=event)
  File "/Users/jomeara/anaconda/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1853, in key_press_event
    self.callbacks.process(s, event)
  File "/Users/jomeara/anaconda/lib/python3.6/site-packages/matplotlib/cbook.py", line 549, in process
    proxy(*args, **kwargs)
  File "/Users/jomeara/anaconda/lib/python3.6/site-packages/matplotlib/cbook.py", line 416, in __call__
    return mtd(*args, **kwargs)
  File "/Users/jomeara/work/Python/pyigm/pyigm/guis/fitlls.py", line 481, in on_key
    self.continuum.wavelength.value-event.xdata))
AttributeError: 'XFitLLSGUI' object has no attribute 'continuum'
Abort

**Comment by profxj** [comment]
Was this after you hit "#"  @astronomeara ?

**Comment by jsribaud** [comment]
I am trying to avoid finishing my syllabi for Monday, so I gave it a spin. 

Working for me - '#' sets the continuum initially, and 'C' allows for resetting. I was able to set an LLS, adjust redshift and column density using 'L', 'g', and 'n/N'. I couldn't remember the b-value adjust, so I tried to change values in the GUI directly, that crashed it immediately. But again, the button-controls I tried worked. I couldn't get 'F' to execute, but that may be the particular LLS I was trying to fit.

**Comment by astronomeara** [comment]
After hitting #, I can re-adjust with C, but I'm not sure why I should have to if the file was already reading in a continuum (I'm assuming the pink line is a continuum from elsewhere).

Also, C shouldn't always make a template QSO continuum.  Imagine if one gives a normalized spectrum from KODIAQ.

R and D still don't work, but *after* hitting #, it doesn't crash the GUI

**Comment by profxj** [comment]
This # "functionality" was added by Team @mifumagalli 

I fear we are stuck with it for now.

Am going to merge and we can deal with other pieces as we need.

**Comment by profxj** [comment]
merging.

**Pull request merged**
