### PR TITLE
igmguesses: more compatibility with linetools

### PR DESCRIPTION
**Pull request by ntejos**
As stated.

### CODE REVIEW

**Review by jnburchett — APPROVED** [review]
igmguesses works again for me...not sure about the H2 stuff

**Comment by ntejos** [comment]
One test is failing because of Python3.5 , otherwise it seems fine.

**Comment by ntejos** [comment]
Seems to be only failing the test from Python3.5, the rest looks fine.

**Comment by profxj** [comment]
Looks good.  Merge when ready

**Pull request merged**
