### PR TITLE
Fix DLA survey stats

### PR DESCRIPTION
**Pull request by profxj**
Addresses bug identified by @mneeleman in Issue #94 

Updated XQ-100 notebook too.

### CODE REVIEW

**Comment by mneeleman** [comment]
OK, that seems to work. However, the problem is indeed for all literature samples (G09 and P03 besides XQ100). Judicious placement of "skip_zem=True" should take care of that.

**Review by mneeleman — COMMENTED** [review]
OK, that seems to work. However, the problem is indeed for all literature samples (G09 and P03 besides XQ100). Judicious placement of "skip_zem=True" should take care of that.

**Comment by profxj** [comment]
Extended.  WIll merge if most tests pass.

**Comment by profxj** [comment]
Failing some tests, but I'm on it.
Merging

**Pull request merged**
