### PR TITLE
Fit LLS GUI

### PR DESCRIPTION
**Pull request by profxj**
Ported the GUI from xastropy and refactored to PyQt5

Tested a bit but not enough.

Docs included

### CODE REVIEW

**Comment by profxj** [comment]
This is ready for review now @astronomeara and @mifumagalli

**Comment by astronomeara** [comment]
Can verify 'F' does not crash if z >> z_em

**Comment by profxj** [comment]
That does not a code review qualify as

**Comment by profxj** [comment]
Merging.

**Pull request merged**
