### PR TITLE
small fixes to handle with python3 compatibility

### PR DESCRIPTION
**Pull request by mifumagalli**
I am testing the code with new grids that include turbulence. In principle, this should work out of the box. However,  in the process, I made small adjustments (I think required for python 3.6). 

Note that the current version of the code fails to create a hdf5, which I believe is associated to this issue: https://stackoverflow.com/questions/23220513/storing-a-list-of-strings-to-a-hdf5-dataset-from-python

I did not find a permanent fix, so I am currently skipping hdf5 file i/o if fails.

### CODE REVIEW

**Review by cwotta — APPROVED** [review]
(1) Forgot about 'b' for Windows machines, sorry (and dict.has_key()...).

(2) Given point (1), should the H5Py write mode also include 'b' (line 404)?

(3) Is this the issue you're facing with H5Py?  Looks like no fixes if we stick with H5Py -- we could potentially switch, but I don't know what that would entail.  https://stackoverflow.com/questions/32654665/python3-crash-when-creating-hdf5-file-via-h5py

**Comment by profxj** [comment]
I really prefer hdf5 if we can keep it.  I think the issue here is 
likely unicode vs. str.   I ran into this issue in specdb and wrote
a simple method to deal with my issue.  See hdf_decode() in this
module:

https://github.com/specdb/specdb/blob/master/specdb/utils.py

If that fixes your trouble, let's stick with hdf5.  Thanks

**Comment by profxj** [comment]
Sorry, my last comment was actually the other way, i.e. 
dealing with reading hdf5 which come in as bytes.

Below is a snippet of code I used to deal with writing to hdf5:

```
    tbl_keys = tbl.keys()
    for key in tbl_keys:
        # Check for unicode
        if 'U' in tbl[key].dtype.__repr__():
            warnings.warn("unicode in column {:s}.  Will convert to str for hdf5".format(key))
            tmp = Column(tbl[key].data.astype(bstr), name=key)
            tbl.remove_column(key)
            tbl[key] = tmp
```

where bstr is defined for Python 2/3 compatability as:

```
try:
    bstr = bytes
except NameError:  # For Python 2
    bstr = str
```

**Comment by mifumagalli** [comment]
@cwotta: Changes are for python 3 on a mac (where I am currently developing). I have not encountered (so far) issues with binary flag in hdf5. Also, not sure b is a write option for hdf5. Skipping for now.

As for HDF5 issue, yes, encoding seems to be the issue. Note that I have not removed hdf5, but only added a safety check so that code does not crash but tries to continue if hdf5 fails. I'll let @cwotta develop a more permanent fix for that bit of the code.

**Review by profxj — APPROVED** [review]
Ok, I'm approving.

**Comment by profxj** [comment]
merging.

**Pull request merged**
