### PR TITLE
NH calculation when NHI is out of bounds

### PR DESCRIPTION
**Pull request by profxj**
As titled.

Tested on COS-Halos by JXP

### CODE REVIEW

**Review by mifumagalli — COMMENTED** [review]
What's the logic behind this? It does not seem to be a self consistent treatment.

**Comment by profxj** [comment]
There are several COS-Halos systems with NHI < 10^15 which falls
off the standard Cloudy grid.  To perform the analysis on these, which
are optically thin, I reset their NHI to the edge of the grid (e.g. 1e15) 
perform the analysis and then shift back down.  That is the intent here
and I think I coded it that way.

**Review by mifumagalli — CHANGES_REQUESTED** [review]
Ok, can I suggest something like this around L80

if(min_NHI > 16):
    warnings.warn('Warning: getting close to optically thick regime')

Then, merge.

**Comment by profxj** [comment]
Good suggestion.  Added.

Merging.

**Pull request merged**
