### PR TITLE
IGMGuesses GUI

### PR DESCRIPTION
**Pull request by profxj**
Moved from xastropy to here.
Added a script to run it and modified setup.py accordingly.

Added a file in docs for @ntejos and @jnburchett to contribute to.
No tests nor Notebook

### CODE REVIEW

**Comment by ntejos** [comment]
I suggest to merge it and test it from there... (?)

**Comment by profxj** [comment]
I can do that if you prefer, but you can just as easy get on this branch and
test it.  I'm hoping that one of you has a moment to add a little documentation
before we merge this.

**Comment by ntejos** [comment]
I see; let's do that then. Will test the branch on my laptop and add some documentation before merging ;)

**Comment by profxj** [comment]
Note that the failing tests are addressed in the reion branch 
and may be ignored here.

**Comment by profxj** [comment]
@ntejos please merge when you feel happy to do so.
I won't be editing it further for now.

**Pull request merged**
